import { createSlice } from '@reduxjs/toolkit';

// Define the initial state
const initialState = {
  languages: [
    {
      id: 'en',
      name: 'English',
      short: 'ENG',
      iconPath: '/assets/flags/gb.svg',
    },
    {
      id: 'ur',
      name: 'Urdu',
      short: 'UR',
      iconPath: '/assets/flags/pak.svg',
    },
  ],
};

// Create a slice for system configuration
const systemConfigSlice = createSlice({
  name: 'systemConfig', // Use singular for the slice name as it represents one configuration object
  initialState,
  reducers: {
    fetchLanguages: (state) => {
      state.languages = state.languages; // Clarify the purpose of the reducer
    },
  },
});

// Export the action creators generated by createSlice
export const { fetchLanguages } = systemConfigSlice.actions;

// Export the reducer as the default export
export default systemConfigSlice.reducer;
